### ISSUE TITLE
[Upvote] Can upvote multiple times.

### ISSUE THREAD

**Issue by nfilzi** [guillaumecabanel/wagon-quotes-on-rails#2]
Bad style.

**Comment by guillaumecabanel** [comment]
I know :( what should I do? I don't know cookie and session yet ;)

**Comment by nfilzi** [comment]
aha you should use cookie and session 😛

**Comment by nfilzi** [comment]
Here you go, something to help you out in setting up a cookie 👉 [resource](http://api.rubyonrails.org/classes/ActionDispatch/Cookies.html)

**Comment by guillaumecabanel** [comment]
Issue solved with commit [cb03095](https://github.com/guillaumecabanel/wagon-quotes-on-rails/commit/cb0309567cf4241e5ec093e1d6133472866b9b64)
